### ISSUE TITLE
Missed Message

### ISSUE THREAD

**Issue by Sbrikky** [Chris1712/unciv-notifier#2]
A turn notification was not sent. Between Aaron's Turn message at 2:08 and Michael's Turn message at 7:48 on the 20th of March there should have been a message for my turn, but there isn't!

**Comment by Chris1712** [comment]
I checked the logs here. The change detection etc worked fine, the issue was rather that the discord api rejected the request with an http error:

Error sending notification: {"message": "504: Gateway Timeout", "code": 0}

My guess is that this was a random discord issue. I could put in a retry process for the http cal, though that would need to account for you taking the turn anyway in the meantime. I did have the idea to give an extra nudge if the same player has been on their turn for too long, that would help in this situation.

**Comment by Chris1712** [comment]
I have added a lame retry in 203132a7f35ff6dfb1ccb54257dd1627fa7545cc
I haven't taken the time to add any nice testing with a mocked failure but if this doesn't work I may be forced to.
